apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-search-app-deployment
  labels:
    app: fastapi-search-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-search-app
  template:
    metadata:
      labels:
        app: fastapi-search-app
    spec:
      serviceAccountName: fastapi-s3-accessor-sa # Kubernetes service account for S3 access
      containers:
      - name: fastapi-search-ecr
        image: 390403867048.dkr.ecr.eu-north-1.amazonaws.com/fastapi-search-ecr:latest
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: fastapi-app-config # For S3_BUCKET
          - secretRef:
              name: aws-s3-credentials
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
